### ISSUE TITLE
App crashes if previousCuePoint is invalid

### ISSUE THREAD

**Issue by prm2612** [googleads/googleads-ima-roku-dai#2]
On this line:
https://github.com/googleads/googleads-ima-roku-dai/blob/d021039638d18e14a0f31b782ea56cc72b759c3c/advanced_example/components/Sdk.xml#L145

If the previousCuePoint is invalid, the application is crashing. Perhaps this line should be moved in the else block.

**Comment by gschoppe** [comment]
The moving into the else block would certainly resolve the issue, but would remove the debugging line for cuepoints that have already played. I'll refactor the if statement slightly to make things more explicit and solve this error

**Comment by gschoppe** [comment]
this is now resolved :)
